#!/usr/bin/env bash
# ============================================================================
# DecisionDNA — one-command Azure provisioning (Phase 1).
#
# Prereqs (Phase 0): an Azure subscription, Azure CLI + Bicep installed, and:
#     az login
#
# Then run:
#     ./scripts/provision-azure.sh
#
# It will: create a resource group, deploy bicep/main.bicep (Azure OpenAI +
# model deployments, AI Search, Cosmos serverless, Key Vault, App Service),
# grant YOU Key Vault + AI access, fetch the OpenAI key, and write a ready-to-use
# .env (MOCK_LLM=0). Finally it verifies connectivity with `npm run test:azure`.
#
# Override any of these via env vars before running:
#     RG=decisiondna-rg LOCATION=eastus2 PREFIX=decisiondna \
#     CHAT_MODEL=gpt-5 CHAT_VERSION=2025-08-07 ./scripts/provision-azure.sh
#
# Tear everything down later with:   az group delete -n "$RG"
# ============================================================================
set -euo pipefail

RG="${RG:-decisiondna-rg}"
LOCATION="${LOCATION:-eastus2}"
PREFIX="${PREFIX:-decisiondna}"
CHAT_MODEL="${CHAT_MODEL:-gpt-5}"
CHAT_VERSION="${CHAT_VERSION:-2025-08-07}"
EMBED_MODEL="${EMBED_MODEL:-text-embedding-3-large}"
DEPLOYMENT="decisiondna-$(date +%Y%m%d%H%M%S)"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
ok()   { printf "\033[32m✓ %s\033[0m\n" "$1"; }
warn() { printf "\033[33m! %s\033[0m\n" "$1"; }
die()  { printf "\033[31m✗ %s\033[0m\n" "$1"; exit 1; }

# ---- preflight -------------------------------------------------------------
command -v az >/dev/null || die "Azure CLI not found. Install it, then 'az login'."
az account show >/dev/null 2>&1 || die "Not logged in. Run: az login"

SUB_NAME="$(az account show --query name -o tsv)"
bold "Provisioning DecisionDNA into subscription: $SUB_NAME"
echo "  Resource group : $RG ($LOCATION)"
echo "  Name prefix    : $PREFIX"
echo "  Chat model     : $CHAT_MODEL ($CHAT_VERSION)"
echo "  Embedding model: $EMBED_MODEL"
echo

# Operator object id → grants you Key Vault Secrets Officer + AI access locally.
OPERATOR_ID="$(az ad signed-in-user show --query id -o tsv 2>/dev/null || echo '')"
[ -n "$OPERATOR_ID" ] && ok "Operator object id: $OPERATOR_ID" || warn "Could not resolve signed-in user object id (Key Vault RBAC for you will be skipped)."

# ---- model availability check (best-effort) --------------------------------
bold "Checking Azure OpenAI model availability in $LOCATION…"
if az cognitiveservices model list -l "$LOCATION" --query "[].model.name" -o tsv 2>/dev/null | grep -qx "$CHAT_MODEL"; then
  ok "$CHAT_MODEL is available in $LOCATION"
else
  warn "$CHAT_MODEL not found in $LOCATION. If the deploy fails on the chat model, re-run with e.g.:"
  warn "    CHAT_MODEL=gpt-4o CHAT_VERSION=2024-11-20 ./scripts/provision-azure.sh"
fi

# ---- resource group --------------------------------------------------------
bold "Creating resource group…"
az group create -n "$RG" -l "$LOCATION" -o none
ok "Resource group ready"

# ---- deploy bicep ----------------------------------------------------------
bold "Deploying infrastructure (this takes ~5–10 min)…"
az deployment group create \
  --resource-group "$RG" \
  --name "$DEPLOYMENT" \
  --template-file bicep/main.bicep \
  --parameters bicep/parameters.json \
  --parameters namePrefix="$PREFIX" location="$LOCATION" openAiLocation="$LOCATION" \
               chatModelName="$CHAT_MODEL" chatModelVersion="$CHAT_VERSION" \
               embeddingModelName="$EMBED_MODEL" operatorObjectId="$OPERATOR_ID" \
  -o none
ok "Deployment complete"

# ---- read outputs ----------------------------------------------------------
get() { az deployment group show -g "$RG" -n "$DEPLOYMENT" --query "properties.outputs.$1.value" -o tsv; }
OPENAI_NAME="$(get openAiName)"
OPENAI_ENDPOINT="$(get openAiEndpoint)"
CHAT_DEPLOYMENT="$(get chatDeploymentName)"
EMBED_DEPLOYMENT="$(get embeddingDeploymentName)"
SEARCH_ENDPOINT="$(get searchEndpoint)"
COSMOS_ENDPOINT="$(get cosmosEndpoint)"
KV_NAME="$(get keyVaultName)"
WEBAPP_HOST="$(get webAppDefaultHostName)"

# ---- fetch the OpenAI key (not exposed as an output by design) --------------
OPENAI_KEY="$(az cognitiveservices account keys list -n "$OPENAI_NAME" -g "$RG" --query key1 -o tsv)"

# ---- write .env ------------------------------------------------------------
bold "Writing .env (MOCK_LLM=0)…"
cat > .env <<EOF
# Generated by scripts/provision-azure.sh on $(date)
MOCK_LLM=0
AZURE_OPENAI_ENDPOINT=$OPENAI_ENDPOINT
AZURE_OPENAI_API_KEY=$OPENAI_KEY
AZURE_OPENAI_API_VERSION=2024-10-21
AZURE_OPENAI_CHAT_DEPLOYMENT=$CHAT_DEPLOYMENT
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=$EMBED_DEPLOYMENT
DECISIONDNA_CONFIDENCE_THRESHOLD=0.6

# Reference (used by the production swap-ins; app runs on Azure OpenAI alone)
AZURE_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
AZURE_COSMOS_ENDPOINT=$COSMOS_ENDPOINT
AZURE_KEY_VAULT_NAME=$KV_NAME
EOF
ok ".env written"

# ---- verify ----------------------------------------------------------------
bold "Verifying Azure OpenAI connectivity…"
set -a; . ./.env; set +a
if npm run -s test:azure; then
  ok "Azure OpenAI reachable — DecisionDNA is now in LIVE mode."
else
  warn "Connectivity check failed — verify the model deployment names/region above."
fi

echo
bold "Done."
echo "  OpenAI endpoint : $OPENAI_ENDPOINT"
echo "  Web App host    : https://$WEBAPP_HOST"
echo "  Run locally     : npm run dev   (now uses real Azure OpenAI)"
echo "  Tear down       : az group delete -n $RG"
